<%@Page Title="Admin's Panel" Language="VB" AutoEventWireup="false" MasterPageFile="~/MasterPage.master" CodeFile="AdminPanel.aspx.vb" Inherits="AdminPanel" %>

<asp:Content ID="ContentAdminPanel" ContentPlaceHolderID="ContentPlaceHolderHome" runat="server">

<div id="contAdminPan"> 

      
            <h1> Administrator's Panel </h1>
      
   <!--Buttons area-->
   <div id="btnsAdmin">

        <ul>
            <li><asp:Button ID="btnUsers" runat="server" Text="Users" Height="30px" Width="120px" Visible="True"/></li>
            <li><asp:Button ID="btnVehicles" runat="server" Text="Vehicles" Height="30px" Width="120px" Visible="True" /></li>
            <li><asp:Button ID="btnCategories" runat="server" Text="Categories" Height="30px" Width="120px" Visible="True" /></li>
            <li><asp:Button ID="btnAddVeh" runat="server" Text="Add Your Vehicle" Height="30px" Width="120px" Visible="true" /></li>
        </ul>
        </div>
   
   <!--Vehicle Gridview-->
   <div id="GridviewsAdmin">
        <br /><asp:GridView ID="gvVehicle" CssClass="GridVeh" runat="server" Width="778px" 
                AutoGenerateColumns="False"
                AutoGenerateSelectButton="True"  
                GridLines="Horizontal" AutoGenerateDeleteButton="True">
                <Columns>
                    <asp:TemplateField HeaderText="Image:">
                        <ItemTemplate>
                            <asp:Image ID="MainImg" runat="server" ImageUrl='<%#"~/Images/"+Eval("MainImage") %>' Height="110" Width="150" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtMainImg" runat="server" Text='<%#"~/Images/"+Eval("MainImage") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Vehicle ID:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtVID" runat="server" Text='<%# Eval("V_ID") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblVID" runat="server" Text='<%# Eval("V_ID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Year:">
                        <ItemTemplate>
                            <asp:Label ID="lblYear" runat="server" Text='<%# Eval("Year") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtYear" runat="server" Text='<%# Eval("Year") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Make:">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtMake" runat="server" Text='<%# Eval("Make") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblMake" runat="server" Text='<%# Eval("Make") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Model:">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtModel" runat="server" Text='<%# Eval("Model") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblModel" runat="server" Text='<%# Eval("Model") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Fuel:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtFuel" runat="server" Text='<%# Eval("Fuel") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblFuel" runat="server" Text='<%# Eval("Fuel") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Engine cc:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEngine" runat="server" Text='<%# Eval("Engine") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblEngine" runat="server" Text='<%# Eval("Engine") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Transmission" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtTrans" runat="server" Text='<%# Eval("Transmission") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblTrans" runat="server" Text='<%# Eval("Transmission") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Color:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtColor" runat="server" Text='<%# Eval("Color") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblColor" runat="server" Text='<%# Eval("Color") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Price:">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtPrice" runat="server" Text='<%# Eval("Price") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            €<asp:Label ID="lblPrice" runat="server" Text='<%# Eval("Price") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Description:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtDesc" runat="server" Text='<%# Eval("Description") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDesc" runat="server" Text='<%# Eval("Description") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Condition:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtCond" runat="server" Text='<%# Eval("Condition") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCond" runat="server" Text='<%# Eval("Condition") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Category:" Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtCatID" runat="server" Text='<%# Eval("[CatID]") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCatID" runat="server" Text='<%# Eval("[CatID]") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField Visible="False">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtSold" runat="server" Text='<%# Eval("Sold") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblSold" runat="server" Text='<%# Eval("Sold") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <!--User Gridview-->
            <asp:GridView ID="gvUser" CssClass="GridVeh" runat="server" Width="695px" 
                AutoGenerateColumns="False"
                AutoGenerateSelectButton="True"  
                GridLines="Horizontal">
            <Columns>
                <asp:TemplateField HeaderText="User ID:">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name:">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtName" runat="server" Text='<%# Eval("Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblName" runat="server" Text='<%# Eval("Name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Surname:">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtSurname" runat="server" Text='<%# Eval("Surname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblSurname" runat="server" Text='<%# Eval("Surname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Username:">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUserName" runat="server" Text='<%# Eval("UserName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblUserName" runat="server" Text='<%# Eval("UserName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Password:">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtPassword" runat="server" Text='<%# Eval("Password") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPassword" runat="server" Text='<%# Eval("Password") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Is Administrator?">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtIsAdmin" runat="server" Text='<%# Eval("IsAdmin") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblIsAdmin" runat="server" Text='<%# Eval("IsAdmin") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            </asp:GridView>
            <!--Category Gridview-->
            <asp:GridView ID="gvCategories" CssClass="GridVeh" runat="server" Width="778px" 
                AutoGenerateColumns="False"  
                GridLines="Horizontal" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True">
                <Columns>
                <asp:TemplateField HeaderText="Category ID" Visible="True">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtCatID" runat="server" Text='<%# Eval("CatID") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblCatID" runat="server" Text='<%# Eval("CatID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Description">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtDesc" runat="server" Text='<%# Eval("Description") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblDesc" runat="server" Text='<%# Eval("Description") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Date Created">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtDateCr" runat="server" Text='<%# Eval("DateCreated") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblDateCr" runat="server" Text='<%# Eval("DateCreated") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
                 </asp:GridView>
   <!--Category Text field-->
   <div id="AdminCatPan">
    
            <asp:Panel ID="pAddCat" runat="server" Height="50px" Width="175px">
            Add New Category:<br />
            <br />
            <asp:TextBox ID="txtDescription" runat="server" Width="100px" Height="20px"></asp:TextBox>
            <asp:Button ID="btnSaveCat" runat="server" Height="26px" Text="Add" Width="67px" /><br />
            <asp:Label ID="lblID" runat="server" Text="Auto Generated ID" Visible="false"></asp:Label><br />
            <asp:Label ID="lblDateCreated" runat="server" Text="Date Created" Visible="false"></asp:Label>
            </asp:Panel>
            <br />
       
   </div>
                      <!--Order Gridview-->
                      <asp:GridView ID="gvOrder" CssClass="GridVeh" runat="server" Width="778px" 
                    AutoGenerateColumns="False"
                    AutoGenerateSelectButton="True"  
                    GridLines="Horizontal">
                    <Columns>
                <asp:TemplateField HeaderText="Order ID">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtOrderID" runat="server" Text='<%# Eval("OrderID") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblOrderID" runat="server" Text='<%# Eval("OrderID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="User ID">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Date and Time">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtDateTime" runat="server" Text='<%# Eval("DateTime") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblDateTime" runat="server" Text='<%# Eval("DateTime") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Total Price">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtTotalPrice" runat="server" Text='<%# Bind("TotalPrice") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblTotalPrice" runat="server" Text='<%# Bind("TotalPrice") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>           
                </asp:GridView>
    <!--OrderLine Gridview (Unbound not like the other gridviews)-->
    <asp:GridView ID="gvOrderLine" CssClass="GridVeh" runat="server">
    </asp:GridView>
      
    <br />
    </div>
    </div>

</asp:Content>