<%@ Page Title="Shopping Cart Page" Language="VB" AutoEventWireup="false" MasterPageFile="~/MasterPage.master" CodeFile="ShoppingCart.aspx.vb" Inherits="ShoppingCart" %>

<asp:Content ID="ContentShoppingCart" ContentPlaceHolderID="ContentPlaceHolderHome" runat="server">

<div id="contShpCrt"> 
      
            <h1> Your Shopping Cart </h1>

            <h2><asp:Label ID="lblZeroRows" runat="server" Text="Label"></asp:Label></h2>
            <br />

    <div id="GridviewVeh">
        <!--Shopping Cart Gridview-->
        <asp:GridView ID="gvShopCart" CssClass="GridVeh" runat="server" Width="778px" 
                AutoGenerateColumns="False" AutoGenerateDeleteButton="True">
            <Columns>
                <asp:TemplateField HeaderText="Date">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtSesDate" runat="server" Text='<%# Eval("SessionDate") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblSesDate" runat="server" Text='<%# Eval("SessionDate") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="User ID">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblUserID" runat="server" Text='<%# Eval("UserID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Vehicle ID">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtV_ID" runat="server" Text='<%# Eval("V_ID") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblV_ID" runat="server" Text='<%# Eval("V_ID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Quantity">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtQty" runat="server" Text='<%# Eval("Quantity") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblQty" runat="server" Text='<%# Eval("Quantity") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:Label ID="lblTotal" Text="Total:" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Price">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtShopPrice" ReadOnly="false" runat="server" Text='<%# Eval("ShopPrice") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblShopPrice" runat="server" Text= '<%# Eval("ShopPrice") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:Label ID="lblTotalPrice" runat="server" />
                    </FooterTemplate> 
                </asp:TemplateField>
            </Columns>
            <FooterStyle HorizontalAlign="Center" />
              <HeaderStyle 
                HorizontalAlign="Center" />
        </asp:GridView>
        <!--Checkout Button-->
        <div id="shopChkOut">

        <p><asp:Button ID="btnCheckout" runat="server" Height="30px" Width="100px" Text="Checkout" /><br /></p>
   
        </div>

    </div>
 </div>



</asp:Content>